import { PDFDocument, StandardFonts, rgb, PDFName } from "pdf-lib";
import { generateBarcodeBuffer } from "./barcode";
import { generateQRCodeBuffer } from "./qrcode";

interface JobCardData {
  jobNumber: string;
  customerName: string;
  poNumber?: string;
  drawingNumber?: string;
  material?: string;
  grade?: string;
  quantity: number;
  unit: string;
  dueDate?: string;
  priority: string;
  status: string;
  remarks?: string;
}

interface DispatchChallanData {
  dispatchNumber: string;
  jobNumber: string;
  customerName: string;
  quantityDispatched: number;
  vehicleNumber?: string;
  transporterName?: string;
  lrNumber?: string;
  driverName?: string;
  driverPhone?: string;
  invoiceNumber?: string;
  invoiceAmount?: number;
  dispatchDate: string;
}

interface DeliveryReceiptData {
  dispatchNumber: string;
  jobNumber: string;
  customerName: string;
  quantityDispatched: number;
  deliveredAt: string;
  deliveredBy?: string;
}

// Create job card PDF
export async function generateJobCardPDF(data: JobCardData): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Header
  page.drawText("JOB TRACK PRO", {
    x: 50,
    y: 800,
    size: 24,
    font: boldFont,
    color: rgb(0.1, 0.2, 0.35),
  });

  page.drawText("JOB CARD", {
    x: 50,
    y: 770,
    size: 16,
    font: boldFont,
    color: rgb(0.2, 0.4, 0.7),
  });

  // Barcode
  try {
    const barcodeBuffer = await generateBarcodeBuffer(data.jobNumber, { height: 30 });
    const barcodeImage = await pdfDoc.embedPng(barcodeBuffer);
    page.drawImage(barcodeImage, { x: 50, y: 720, width: 200, height: 40 });
  } catch {
    page.drawText(`Barcode: ${data.jobNumber}`, { x: 50, y: 730, size: 10, font });
  }

  // QR Code
  try {
    const qrBuffer = await generateQRCodeBuffer(`${process.env.FRONTEND_URL || "http://localhost:3000"}/track/${data.jobNumber}`, { width: 100 });
    const qrImage = await pdfDoc.embedPng(qrBuffer);
    page.drawImage(qrImage, { x: 450, y: 720, width: 100, height: 100 });
  } catch {
    // QR code optional
  }

  // Job details
  let y = 680;
  const lineHeight = 25;

  const details = [
    ["Job Number", data.jobNumber],
    ["Customer", data.customerName],
    ["PO Number", data.poNumber || "-"],
    ["Drawing No.", data.drawingNumber || "-"],
    ["Material", data.material || "-"],
    ["Grade", data.grade || "-"],
    ["Quantity", `${data.quantity} ${data.unit}`],
    ["Priority", data.priority],
    ["Status", data.status.replace(/_/g, " ").toUpperCase()],
    ["Due Date", data.dueDate || "-"],
    ["Remarks", data.remarks || "-"],
  ];

  for (const [label, value] of details) {
    page.drawText(`${label}:`, { x: 50, y, size: 11, font: boldFont });
    page.drawText(String(value), { x: 180, y, size: 11, font });
    y -= lineHeight;
  }

  // Footer
  page.drawText("Generated by JobTrack Pro", {
    x: 50,
    y: 50,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  page.drawText(new Date().toLocaleDateString(), {
    x: 450,
    y: 50,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return Buffer.from(await pdfDoc.save());
}

// Create dispatch challan PDF
export async function generateDispatchChallanPDF(data: DispatchChallanData): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Header
  page.drawText("DISPATCH CHALLAN", {
    x: 200,
    y: 800,
    size: 20,
    font: boldFont,
    color: rgb(0.1, 0.2, 0.35),
  });

  page.drawText(`Dispatch No: ${data.dispatchNumber}`, {
    x: 50,
    y: 760,
    size: 12,
    font: boldFont,
  });

  page.drawText(`Date: ${data.dispatchDate}`, {
    x: 400,
    y: 760,
    size: 12,
    font,
  });

  // Horizontal line
  page.drawLine({
    start: { x: 50, y: 750 },
    end: { x: 545, y: 750 },
    thickness: 1,
    color: rgb(0, 0, 0),
  });

  // Job details
  let y = 720;
  const jobDetails = [
    ["Job Number", data.jobNumber],
    ["Customer", data.customerName],
    ["Quantity Dispatched", String(data.quantityDispatched)],
    ["Vehicle Number", data.vehicleNumber || "-"],
    ["Transporter", data.transporterName || "-"],
    ["L.R. Number", data.lrNumber || "-"],
    ["Driver Name", data.driverName || "-"],
    ["Driver Phone", data.driverPhone || "-"],
    ["Invoice Number", data.invoiceNumber || "-"],
    ["Invoice Amount", data.invoiceAmount ? `₹${data.invoiceAmount.toLocaleString()}` : "-"],
  ];

  for (const [label, value] of jobDetails) {
    page.drawText(`${label}:`, { x: 50, y, size: 11, font: boldFont });
    page.drawText(String(value), { x: 200, y, size: 11, font });
    y -= 22;
  }

  // Signature lines
  y = 200;
  page.drawText("Authorized Signature", { x: 50, y, size: 10, font });
  page.drawLine({
    start: { x: 50, y: y - 5 },
    end: { x: 200, y: y - 5 },
    thickness: 0.5,
  });

  page.drawText("Receiver's Signature", { x: 350, y, size: 10, font });
  page.drawLine({
    start: { x: 350, y: y - 5 },
    end: { x: 500, y: y - 5 },
    thickness: 0.5,
  });

  return Buffer.from(await pdfDoc.save());
}

// Create delivery receipt PDF
export async function generateDeliveryReceiptPDF(data: DeliveryReceiptData): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Header
  page.drawText("DELIVERY RECEIPT", {
    x: 200,
    y: 800,
    size: 20,
    font: boldFont,
    color: rgb(0.1, 0.2, 0.35),
  });

  // Receipt details
  let y = 750;
  const details = [
    ["Dispatch Number", data.dispatchNumber],
    ["Job Number", data.jobNumber],
    ["Customer", data.customerName],
    ["Quantity Received", String(data.quantityDispatched)],
    ["Delivered At", data.deliveredAt],
    ["Received By", data.deliveredBy || "-"],
  ];

  for (const [label, value] of details) {
    page.drawText(`${label}:`, { x: 50, y, size: 12, font: boldFont });
    page.drawText(String(value), { x: 220, y, size: 12, font });
    y -= 30;
  }

  // Confirmation text
  y = 300;
  page.drawText("I hereby confirm that the above-mentioned goods have been received", {
    x: 50,
    y,
    size: 11,
    font,
  });
  page.drawText("in good condition and as per the order specifications.", {
    x: 50,
    y: y - 20,
    size: 11,
    font,
  });

  // Signature
  y = 150;
  page.drawText("Customer Signature & Stamp", { x: 50, y, size: 10, font });
  page.drawLine({
    start: { x: 50, y: y - 5 },
    end: { x: 250, y: y - 5 },
    thickness: 0.5,
  });

  return Buffer.from(await pdfDoc.save());
}

// Create invoice template PDF
export async function generateInvoicePDF(data: {
  invoiceNumber: string;
  invoiceDate: string;
  jobNumber: string;
  customerName: string;
  customerAddress?: string;
  items: Array<{ description: string; quantity: number; rate: number; amount: number }>;
  totalAmount: number;
  taxAmount?: number;
  grandTotal: number;
}): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Header
  page.drawText("TAX INVOICE", {
    x: 220,
    y: 800,
    size: 22,
    font: boldFont,
    color: rgb(0.1, 0.2, 0.35),
  });

  // Invoice details
  let y = 760;
  page.drawText(`Invoice No: ${data.invoiceNumber}`, { x: 50, y, size: 11, font: boldFont });
  page.drawText(`Date: ${data.invoiceDate}`, { x: 350, y, size: 11, font });
  page.drawText(`Job No: ${data.jobNumber}`, { x: 50, y: y - 20, size: 11, font });

  // Customer info
  y = 700;
  page.drawText("Bill To:", { x: 50, y, size: 11, font: boldFont });
  page.drawText(data.customerName, { x: 50, y: y - 20, size: 11, font });
  if (data.customerAddress) {
    page.drawText(data.customerAddress, { x: 50, y: y - 40, size: 10, font });
  }

  // Table header
  y = 620;
  page.drawText("Description", { x: 50, y, size: 10, font: boldFont });
  page.drawText("Qty", { x: 300, y, size: 10, font: boldFont });
  page.drawText("Rate", { x: 370, y, size: 10, font: boldFont });
  page.drawText("Amount", { x: 460, y, size: 10, font: boldFont });

  page.drawLine({
    start: { x: 50, y: y - 5 },
    end: { x: 545, y: y - 5 },
    thickness: 0.5,
  });

  // Items
  y -= 25;
  for (const item of data.items) {
    page.drawText(item.description, { x: 50, y, size: 10, font });
    page.drawText(String(item.quantity), { x: 300, y, size: 10, font });
    page.drawText(`₹${item.rate.toLocaleString()}`, { x: 370, y, size: 10, font });
    page.drawText(`₹${item.amount.toLocaleString()}`, { x: 460, y, size: 10, font });
    y -= 20;
  }

  // Totals
  y -= 20;
  page.drawLine({
    start: { x: 350, y: y + 10 },
    end: { x: 545, y: y + 10 },
    thickness: 0.5,
  });

  page.drawText("Subtotal:", { x: 370, y, size: 10, font: boldFont });
  page.drawText(`₹${data.totalAmount.toLocaleString()}`, { x: 460, y, size: 10, font });

  if (data.taxAmount) {
    y -= 20;
    page.drawText("Tax:", { x: 370, y, size: 10, font: boldFont });
    page.drawText(`₹${data.taxAmount.toLocaleString()}`, { x: 460, y, size: 10, font });
  }

  y -= 25;
  page.drawText("Grand Total:", { x: 370, y, size: 12, font: boldFont });
  page.drawText(`₹${data.grandTotal.toLocaleString()}`, { x: 450, y, size: 12, font: boldFont });

  // Footer
  page.drawText("Thank you for your business!", {
    x: 200,
    y: 100,
    size: 12,
    font,
    color: rgb(0.2, 0.4, 0.7),
  });

  return Buffer.from(await pdfDoc.save());
}
